site_name: Documentação

nav:
  - Instruções mkdocs: "index.md"
  - Atas de Reunião:
    - Ata 1: "atas-reuniao/ata-reuniao-1.md"
    - Ata 2: "atas-reuniao/ata-reuniao-2.md"
    - Ata 3: "atas-reuniao/ata-reuniao-3.md"
    - Ata 4: "atas-reuniao/ata-reuniao-4.md"

  -Visão de produto:
    -Lean Inception: "visao-de-product.pdf"
theme:
  name: material
