site_name: Documentação

nav:
  - Home: "index.md"
  
  - Documento de arquitetura: "Arquitetura/Documento_Arquitetura.md"
  
  - Pareamento de duplas: "Organização da equipe/Pareamento_duplas.md"
  
  - Atas de Reunião:             
    - Ata 1: "atas-reuniao/ata-reuniao-1.md" 
    - Ata 2: "atas-reuniao/ata-reuniao-2.md" 
    - Ata 3: "atas-reuniao/ata-reuniao-3.md"
    - Ata 4: "atas-reuniao/ata-reuniao-4.md"
    - Ata 5: "atas-reuniao/ata-reuniao-5.md"
    - Ata 6: "atas-reuniao/ata-reuniao-6.md"
    - Ata 7: "atas-reuniao/ata-reuniao-7.md"
    - Ata 8: "atas-reuniao/ata-reuniao-7-11.md"
    - Ata 9: "atas-reuniao/ata-reuniao-9-11.md"
    
    

theme:
  name: material
  
  
