site_name: Documentação

nav:
  - Instruções mkdocs: "index.md"
  - Documento de arquitetura: "Documento_Arquitetura.md"
  - Atas de Reunião:             
    - Ata 1: "atas-reuniao/ata-reuniao-1.md" 
    - Ata 2: "atas-reuniao/ata-reuniao-2.md" 
    - Ata 3: "atas-reuniao/ata-reuniao-3.md"
    - Ata 4: "atas-reuniao/ata-reuniao-4.md"
    - Ata 5: "atas-reuniao/ata-reuniao-5.md"

theme:
  name: material
  
  # Adicione o bloco 'palette' para configurar o tema claro e o tema escuro.
  palette:
    # 1. Configuração do Tema CLARO (Day mode)
    - media: "(prefers-color-scheme: light)" # Aplica-se se o SO for claro
      scheme: default                        # Esquema padrão do Material (fundo claro)
      primary: indigo                        # Cor principal de destaque (cabeçalho, etc.)
      accent: deep orange                    # Cor de acento (links, botões)
      toggle:
        icon: material/brightness-7          # Ícone de Sol
        name: Trocar para modo escuro

    # 2. Configuração do Tema ESCURO (Night mode)
    - media: "(prefers-color-scheme: dark)"  # Aplica-se se o SO for escuro
      scheme: slate                          # Esquema escuro do Material (fundo cinza escuro)
      primary: blue grey                     # Cor principal de destaque no escuro
      accent: deep orange                    # Cor de acento
      toggle:
        icon: material/brightness-4          # Ícone de Lua
        name: Trocar para modo claro       
